---
# This playbook prints a simple debug message
- name: Echo 
  hosts: servers
  remote_user: root
# connection: local

  tasks:
  - name: Print debug
    ansible.builtin.debug:
      msg: Hello, world!

  - name: Print ping
    ansible.builtin.ping:
      data: Pong
